const actionsTypes = {
  REQUESTED_JOBS_LIST: 'REQUESTED_JOBS_LIST',
  REQUESTED_JOBS_LIST_ASYNC: 'REQUESTED_JOBS_LIST_ASYNC',
  REQUESTED_JOBS_LIST_SUCCESS: 'REQUESTED_JOBS_LIST_SUCCESS',
  REQUESTED_JOBS_LIST_ERROR: 'REQUESTED_JOBS_LIST_ERROR',

  REQUESTED_JOB: 'REQUESTED_JOB',
  REQUESTED_JOB_ASYNC: 'REQUESTED_JOB_ASYNC',
  REQUESTED_JOB_SUCCESS: 'REQUESTED_JOB_SUCCESS',
  REQUESTED_JOB_ERROR: 'REQUESTED_JOB_ERROR',
};

export default actionsTypes;
